### ISSUE TITLE
Example Provided does not work

### ISSUE THREAD

**Issue by klvnnsrikanth** [graph-quilt/graphql-orchestrator-java#158]
**Describe the bug**

Example provided as it is on the README file doesn't work.

**To Reproduce**

Create a new project, add the code as mentioned in the README file and run the main method. 

**Expected behavior**

Response

**Additional context**
Seeing exception as below
```java
Exception in thread "main" java.lang.NoSuchFieldError: EOF_TOKEN
	at org.eclipse.xtext.parser.antlr.Lexer.nextToken(Lexer.java:60)
	at org.antlr.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:143)
	at org.antlr.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:137)
	at org.antlr.runtime.BufferedTokenStream.fill(BufferedTokenStream.java:286)
	at org.antlr.runtime.BufferedTokenStream.toString(BufferedTokenStream.java:251)
	at org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser.parse(AbstractInternalAntlrParser.java:586)
	at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.doParse(AbstractAntlrParser.java:103)
	at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.parse(AbstractAntlrParser.java:85)
	at org.eclipse.xtext.parser.antlr.AbstractAntlrParser.doParse(AbstractAntlrParser.java:63)
	at org.eclipse.xtext.parser.AbstractParser.parse(AbstractParser.java:34)
	at org.eclipse.xtext.resource.XtextResource.doLoad(XtextResource.java:178)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLoad(LazyLinkingResource.java:115)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at com.intuit.graphql.orchestrator.xtext.XtextResourceSetBuilder.createResourceFrom(XtextResourceSetBuilder.java:107)
	at com.intuit.graphql.orchestrator.xtext.XtextResourceSetBuilder.createGraphqlResourceFrom(XtextResourceSetBuilder.java:118)
	at com.intuit.graphql.orchestrator.xtext.XtextResourceSetBuilder.createGraphqlResourceFromString(XtextResourceSetBuilder.java:114)
	at com.intuit.graphql.orchestrator.xtext.XtextResourceSetBuilder.lambda$build$0(XtextResourceSetBuilder.java:91)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at com.intuit.graphql.orchestrator.xtext.XtextResourceSetBuilder.build(XtextResourceSetBuilder.java:89)
	at com.intuit.graphql.orchestrator.xtext.XtextGraphBuilder.build(XtextGraphBuilder.java:24)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.intuit.graphql.orchestrator.stitching.XtextStitcher.stitch(XtextStitcher.java:101)
	at com.intuit.graphql.orchestrator.stitching.SchemaStitcher.stitchGraph(SchemaStitcher.java:36)
	at org.example.Main.main(Main.java:19)
```

**Comment by CNAChino** [comment]
@klvnnsrikanth I just tried the example and works fine.  Can you share files?  I'll try to replicate on my end

**Comment by klvnnsrikanth** [comment]
I just now tried with maven and that seems to work. If I use gradle it doesn't work.

**Comment by CNAChino** [comment]
@klvnnsrikanth yes, we shall start working on Java 11 this upcoming quarter.

**Comment by klvnnsrikanth** [comment]
@CNAChino Java 11 is also EOL by Sep 2023, better to move to Java 17 directly or have to releases one supporting JAVA 11 and another for JAVA 17.
